fixed: https://github.com/Pidan/pidan/issues/4; Beautified the user interface

diff --git a/pidan b/pidan
--- a/pidan
+++ b/pidan
@@ -25,6 +25,20 @@ white(){
     echo -e "\033[37m\033[01m$1\033[0m"
 }
 
+blue(){
+    echo -e "\033[34m\033[01m$1\033[0m"
+}
+
+# cleanup and exit
+cleanup_and_exit() {
+    if [[ -f "gitignore.pidan" ]]; then
+        rm "gitignore.pidan"
+    fi
+    exit 0
+}
+
+trap 'cleanup_and_exit' INT SIGTERM SIGHUP
+
 # local version
 function local_version() {
     echo "v0.1.1"
@@ -111,23 +125,23 @@ function check_upgrade() {
 # initialize gitignore file
 function init_gitignore() {
     # check if the .gitignore file exists
-    # if [ -f ".gitignore" ]; then
-    #     echo ".gitignore file already exists."
-    #     exit 1
-    # else
+    if [ -f ".gitignore" ]; then
+        red "gitignore file already exists. You need to delete it first. Run 'rm .gitignore'"
+        exit 1
+    else
         echo "Initializing gitignore file"
-        echo "============================="
         # Step 1, Choose your OS
+        blue "Choose your OS:"
         os_list=($(init_os))
         PS3="Enter the number corresponding to your choice: "
         os_options=("${os_list[@]}" "skip") 
         select os in "${os_options[@]}"; do
         if [[ -n $os ]]; then
             if [[ "$os" == "skip" ]]; then
-                yellow "Skipped"
+                yellow "...Skipped"
             else
                 get_gitignore "os" "$os"
-                green "OS gitignore file appended."
+                green "...Done"
             fi
             break
         else
@@ -136,17 +150,17 @@ function init_gitignore() {
         done
 
         # Step 2, Choose your language
-        echo "------------------------"
+        blue "Choose your language:"
         lang_list=($(init_language))
         PS3="Enter the number corresponding to your choice: "
         lang_options=("${lang_list[@]}" "skip")
         select lang in "${lang_options[@]}"; do
         if [[ -n $lang ]]; then
             if [[ "$lang" == "skip" ]]; then
-                yellow "Skipped"
+                yellow "...Skipped"
             else
                 get_gitignore "language" "$lang"
-                green "Language gitignore file appended."
+                green "...Done"
             fi
             break
         else
@@ -155,17 +169,17 @@ function init_gitignore() {
         done
 
         # Step 3, Choose your framework
-        echo "------------------------"
+        blue "Choose your framework:"
         framework_list=($(init_framework))
         PS3="Enter the number corresponding to your choice: "
         framework_options=("${framework_list[@]}" "skip")
         select framework in "${framework_options[@]}"; do
         if [[ -n $framework ]]; then
             if [[ "$framework" == "skip" ]]; then
-                yellow "Skipped"
+                yellow "...Skipped"
             else
                 get_gitignore "framework" "$framework"
-                green "Framework gitignore file appended."
+                green "...Done"
             fi
             break
         else
@@ -174,17 +188,17 @@ function init_gitignore() {
         done
 
         # Step 4, Choose your IDE
-        echo "------------------------"
+        blue "Choose your IDE:"
         ide_list=($(init_ide))
         PS3="Enter the number corresponding to your choice: "
         ide_options=("${ide_list[@]}" "skip")
         select ide in "${ide_options[@]}"; do
         if [[ -n $ide ]]; then
             if [[ "$ide" == "skip" ]]; then
-                yellow "Skipped"
+                yellow "...Skipped"
             else
                 get_gitignore "ide" "$ide"
-                green "IDE gitignore file appended."
+                green "...Done"
             fi
             break
         else
@@ -193,8 +207,8 @@ function init_gitignore() {
         done
 
         # Step 5, Comfirm
-        echo "------------------------"
-        echo "Summary:"
+        echo "-------------------------------"
+        blue "Summary:"
         echo "Operating System: $(if [[ "$os" == "skip" ]]; then yellow "$os"; else green "$os"; fi)"
         echo "Programming Language: $(if [[ "$lang" == "skip" ]]; then yellow "$lang"; else green "$lang"; fi)"
         echo "Framework: $(if [[ "$framework" == "skip" ]]; then yellow "$framework"; else green "$framework"; fi)"
@@ -213,7 +227,7 @@ function init_gitignore() {
         fi
         echo "============================="
 
-    # fi
+    fi
 }
 
 main(){
